#!/bin/bash

tmpdir=""
trap 'rm -rf "$tmpdir"' 0 1 2 3 15
tmpdir=`mktemp -d jsqrcode_XXXXXXXX`

pushd $tmpdir
git clone https://github.com/LazarSoft/jsqrcode.git
git clone https://github.com/mishoo/UglifyJS.git
popd

for f in grid.js version.js detector.js formatinf.js errorlevel.js bitmat.js \
        datablock.js bmparser.js datamask.js rsdecoder.js gf256poly.js gf256.js\
        decoder.js qrcode.js findpat.js alignpat.js databr.js ; do
    cat $tmpdir/jsqrcode/src/$f
done | js $tmpdir/UglifyJS/bin/uglifyjs > jsqrcode.min.js


